### ISSUE TITLE
Invalid role id issue

### ISSUE THREAD

**Issue by QtClem** [iDarkLightning/LiteBot#3]
Tying to configure bot role id permissions via discord settings command does not work, adding specific users does still work however. However direct edit of config/settings.json will work.
https://youtu.be/aInbhre3QkA
https://i.imgur.com/d3Ov3cz.png (setting.json edit with same id tried in video)

**Comment by hp3721** [comment]
https://github.com/iDarkLightning/LiteBot/blob/05f35d2c3894982e184921967c3ee1d17e8d6d6e/plugins/system/settings/menus.py#L371 [discord.Role.id](https://discordpy.readthedocs.io/en/stable/api.html?highlight=role%20id#discord.Role.id) returns an integer and [discord.Message.content](https://discordpy.readthedocs.io/en/stable/api.html?highlight=message#discord.Message.content) returns a string. This comparison would always result to false. Some potential fixes are converting the integer role id to a string `str(i.id)` or using [discord.Guild.get_role()](https://discordpy.readthedocs.io/en/stable/api.html?highlight=fetch_roles#discord.Guild.get_role) with `int(message.content)` and replacing `IndexError` with `ValueError` instead of directly using the API call to get roles and comparing their role ids.

**Comment by iDarkLightning** [comment]
Ah, yeah. I am an idiot. Just didn't occur to me for some reason

**Comment by iDarkLightning** [comment]
It's been fixed
